package pages;

import base.BasePage;
import org.openqa.selenium.By;

public class RoleAndPageAuthorizationPage extends BasePage {
    By roleAndPageAuthorizationPageSubLeftMenuButton = By.cssSelector(".MuiCollapse-wrapperInner div:nth-of-type(5) > .MuiButtonBase-root");
    By roleAndPageAuthorizationPageSaveButton = By.cssSelector(".css-9urz1a");
    By roleAndPageAuthorizationPageRoleName = By.xpath("//div[.='ADMIN']");
    By roleAndPageAuthorizationPageModuleName = By.xpath("//div[.='\u200B']");
    By roleAndPageAuthorizationPageLoginManagementCheckbox = By.cssSelector("[value='883b6078-51cc-444f-8e2a-28f428e08344']");
    By roleAndPageAuthorizationPageUserManagementCheckbox = By.cssSelector("[value='5cb40b57-e6be-465a-8606-52e43e0647a8']");
    By roleAndPageAuthorizationPageForgetPasswordCheckbox = By.cssSelector("[value='e71ffc88-2480-46e4-abf6-e14246c7ec09']");
    By roleAndPageAuthorizationPageUpdatePasswordCheckbox = By.cssSelector("[value='3f66c831-fd97-44d1-a6b4-16f4296ffcde']");
    By roleAndPageAuthorizationPageDeletedSelectedUserCheckbox = By.cssSelector("[value='7a6908cf-f844-4f39-b92e-9fd3303ae334']");
    By roleAndPageAuthorizationPageGetUserByIdCheckbox = By.cssSelector("[value='84315630-6797-476c-a5f4-7d8e2fd3833c']");
    By roleAndPageAuthorizationPageNewPasswordCheckbox = By.cssSelector("[value='44fbd269-12d2-4b63-977b-35e2a3ac8f93']");
    By roleAndPageAuthorizationPageListUserCheckbox = By.cssSelector("[value='d55b9294-e10e-49c6-8b42-0fe577472f76']");
    By roleAndPageAuthorizationPageUpdateUserCheckbox = By.cssSelector("[value='c15a7419-27aa-4929-a88a-710610545f68']");
    By roleAndPageAuthorizationPageExportUserCheckbox = By.cssSelector("[value='55724b35-dbbf-43c2-90fd-f96c4c446468']");
    By roleAndPageAuthorizationPageRoleManagementCheckbox = By.cssSelector("[value='0488d6cb-8e82-4a5b-bb12-6abdd80a6754']");
    By roleAndPageAuthorizationPageDeletedSelectedRolesCheckbox = By.cssSelector("[value='99003fc8-9a39-49ee-b350-26885ed6fa62']");
    By roleAndPageAuthorizationPageCreateRoleCheckbox = By.cssSelector("[value='9d68ec6c-f6d7-4309-a801-6677978f6a08']");
    By roleAndPageAuthorizationPageFetchSelectedRoleCheckbox = By.cssSelector("[value='1f2cdbd8-614e-4f41-a2ce-b4d18d7b54e4']");
    By roleAndPageAuthorizationPageUpdateRoleCheckbox = By.cssSelector("[value='b771b5b9-8ae2-41fa-af17-abda003cc1da']");
    By roleAndPageAuthorizationPageListMakerAndCheckerPendingCheckbox = By.cssSelector("[value='fecee26f-a2f1-4d78-9a79-ac0c5d8ed7e4']");
    By roleAndPageAuthorizationPageUserGroupManagementCheckbox = By.cssSelector("[value='d80174c8-e8b2-4d83-84e3-dd182d2fbdd0']");
    By roleAndPageAuthorizationPageUpdateUserGroupCheckbox = By.cssSelector("[value='0978a27d-44fe-40f5-8dcd-ba6783ae5417']");
    By roleAndPageAuthorizationPageFetchSelectedUserGroupCheckbox = By.cssSelector("[value='772ae248-4d84-425c-8871-f0302e440d3e']");
    By roleAndPageAuthorizationPageDeletedSelectedUserGroupCheckbox = By.cssSelector("[value='af62d208-f2b3-4599-9f43-cf2921dde459']");
    By roleAndPageAuthorizationPageListUserGroupCheckbox = By.cssSelector("[value='8c785fb3-d86d-4758-9e94-b91f2e4c33b7']");
    By roleAndPageAuthorizationPageCreateUserGroupCheckbox = By.cssSelector("[value='f7260bed-f162-40e4-856a-4eb313cf6b1a']");
    By roleAndPageAuthorizationPageUserGroupAndRoleAuthorizationCheckbox = By.cssSelector("[value='44219758-0b19-4661-bd7b-367d97753595']");
    By roleAndPageAuthorizationPageAddRoleToUserGroupCheckbox = By.cssSelector("[value='a1bd185f-2cf3-453c-b7bd-150d0f5acec5']");
    By roleAndPageAuthorizationPageRoleAndPageManagementCheckbox = By.cssSelector("[value='a4e199f6-7a5f-4f85-a101-7812fde541f9']");
    By roleAndPageAuthorizationPageGetPermissionForRoleAndPageCheckbox = By.cssSelector("[value='59ffc4b2-0823-4166-bc32-215463e8bfc1']");
    By roleAndPageAuthorizationPageAddPermissionForRoleAndPageCheckbox = By.cssSelector("[value='bf639a66-d45b-4f47-8f10-65aa7fdcd145']");
    By roleAndPageAuthorizationPageWaitingApprovalsCheckbox = By.cssSelector("[value='0814c0db-362e-4a68-a7c7-e679bfcfe80d']");
    By roleAndPageAuthorizationPageMakerAndCheckerCheckbox = By.cssSelector("[value='7053e0f8-fca6-428a-80db-723ccfc6bc0f']");
    By roleAndPageAuthorizationPageMakerAndCheckerExportCheckbox = By.cssSelector("[value='abec664a-12c1-4479-a48e-f671ba8ec36c']");
    By roleAndPageAuthorizationPageDownloadFilesCheckbox = By.cssSelector("[value='1173d02b-5a8e-40ac-b524-6f901d87b914']");
    By roleAndPageAuthorizationPageUpdateMakerAndCheckerCheckbox = By.cssSelector("[value='6a03966e-2f39-4fa8-8d92-52e42212a7d7']");
    By roleAndPageAuthorizationPageListMakerAndCheckerCheckbox = By.cssSelector("[value='8753275b-39aa-4fa9-b90d-515792c74332']");
    By roleAndPageAuthorizationPagePaymentManagementCheckbox = By.cssSelector("[value='7d320381-0f3b-4c9d-9faf-b72ebcbb3d44']");
    By roleAndPageAuthorizationPageBankManagementCheckbox = By.cssSelector("[value='55348921-347a-4701-834b-5f1f736cbd29']");
    By roleAndPageAuthorizationPageCreateBankCheckbox = By.cssSelector("[value='7bbc88b4-ff13-4a90-85d1-aef7912341bf']");
    By roleAndPageAuthorizationPageExportBankCheckbox = By.cssSelector("[value='cc9aa247-edc3-40b4-aa58-331a14878b35']");
    By roleAndPageAuthorizationPageUpdateBankCheckbox = By.cssSelector("[value='6bc2fc03-9ae9-45f7-b200-5a1c92a5ce94']");
    By roleAndPageAuthorizationPageGetBankCheckbox = By.cssSelector("[value='df91e097-b43f-4573-afdf-5eb435a369c1']");
    By roleAndPageAuthorizationPagePosManagementCheckbox = By.cssSelector("[value='ee6f44d1-3213-4a6e-9319-88fc30349d6a']");
    By roleAndPageAuthorizationPageGetPosCheckbox = By.cssSelector("[value='db00ce08-6b05-4737-b982-c032a18a860b']");
    By roleAndPageAuthorizationPageUpdatePosCheckbox = By.cssSelector("[value='663a2350-6dc9-4781-adef-39b0759112f6']");
    By roleAndPageAuthorizationPageGetDetailsOfPosCheckbox = By.cssSelector("[value='3e89fef9-41ae-4643-acb2-5ef36640b845']");
    By roleAndPageAuthorizationPageCreatePosCheckbox = By.cssSelector("[value='ddcb09c4-6285-4aa5-873f-7d2f12188e33']");
    By roleAndPageAuthorizationPageExportPosCheckbox = By.cssSelector("[value='741af29d-9c6c-49c5-afe9-7413c43c89f6']");
    By roleAndPageAuthorizationPagePaymentRecordsCheckbox = By.cssSelector("[value='c4872d4f-3b2f-4e63-b84a-6106e77663d5']");
    By roleAndPageAuthorizationPageGetPaymentCheckbox = By.cssSelector("[value='0b5d59e1-5daf-437b-aa16-c03deb0afeb1']");
    By roleAndPageAuthorizationPageGetDetailsOfPaymentCheckbox = By.cssSelector("[value='bf724cae-70ba-4eb6-a5a5-59cf930282ba']");
    By roleAndPageAuthorizationPageExportPaymentCheckbox = By.cssSelector("[value='25ff0b10-b5a4-4df3-9d14-04703c7381a3']");
    By roleAndPageAuthorizationPageCreatePaymentCheckbox = By.cssSelector("[value='62ae45f8-5c21-4460-aa3d-d5d2eab9434e']");
    By roleAndPageAuthorizationPageSoftPosCreateRefundCheckbox = By.cssSelector("[value='c712b76a-13eb-4e0e-91f2-4d4e40dbf727']");
    By roleAndPageAuthorizationPagePaymentTransactionsCheckbox = By.cssSelector("[value='237017d7-c9d0-4765-beec-96e12b49983d']");
    By roleAndPageAuthorizationPageGetDetailsOfTransactionCheckbox = By.cssSelector("[value='3fdaf170-e04a-4008-a2e6-a15183da80bd']");
    By roleAndPageAuthorizationPageGetPaymentTransactionsCheckbox = By.cssSelector("[value='6b3502c3-11a9-42d6-bf94-de0e13bc0627']");
    By roleAndPageAuthorizationPageExportPaymentTransactionsCheckbox = By.cssSelector("[value='239af709-a757-4067-8087-7e13dbd34d44']");
    By roleAndPageAuthorizationPageMerchantManagementCheckbox = By.cssSelector("[value='2c31c50f-cd06-42c2-bbf1-39285d9e104a']");
    By roleAndPageAuthorizationPageMerchantsCheckbox = By.cssSelector("[value='8d894fd2-409b-4a3e-97a8-9b80c4f517fa']");
    By roleAndPageAuthorizationPageListMerchantsCheckbox = By.cssSelector("[value='6d926967-faac-4583-95f3-2ffc6c0a3a00']");
    By roleAndPageAuthorizationPageExportCheckbox = By.cssSelector("[value='576eee33-a00a-40b5-a924-e6823d60eb10']");
    By roleAndPageAuthorizationPageUpdateMerchantStatusCheckbox = By.cssSelector("[value='1c9e0bcd-ad9e-44c9-862a-20a8c8e47063']");
    By roleAndPageAuthorizationPageGetMerchantCheckbox = By.cssSelector("[value='2e0f125a-a888-4f5a-a32a-6fe566698137']");
    By roleAndPageAuthorizationPageUpdateMerchantCheckbox = By.cssSelector("[value='73cc36ca-5219-4bae-ab7e-f444019a9c54']");
    By roleAndPageAuthorizationPageGetSubMerchantDetailCheckbox = By.cssSelector("[value='404427ef-4be6-4705-a8b9-b22986a91295']");
    By roleAndPageAuthorizationPageListSubMerchantCheckbox = By.cssSelector("[value='85db2d76-427e-49e0-92d4-6a55c32e5d8a']");
    By roleAndPageAuthorizationPageReportsCheckbox = By.cssSelector("[value='6c47c7d0-1a47-4a66-9650-7c10641b1f06']");
    By roleAndPageAuthorizationPageMerchantPayoutReportsCheckbox = By.cssSelector("[value='6c47c7d0-1a47-4a66-9650-7c10641b1f06']");
    By roleAndPageAuthorizationPageCreatePayoutTransactionCheckbox = By.cssSelector("[value='002f8a76-2c0d-463d-98d2-bf77b6d43ff1']");
    By roleAndPageAuthorizationPageCreatePayoutReportCheckbox = By.cssSelector("[value='b89f05ab-d180-4d34-80a2-378a19fb5fd6']");
    By roleAndPageAuthorizationPageFinanceAndAccountingManualAdjustmentCheckbox = By.cssSelector("[value='1ba87fea-d36e-40bd-8ec2-84be8d379de9']");
    By roleAndPageAuthorizationPageGetManualCorrectionCheckbox = By.cssSelector("[value='924a4444-4b34-4e2f-9308-e6c6abf27ce9']");
    By roleAndPageAuthorizationPageCreateManualCorrectionCheckbox = By.cssSelector("[value='15a6176e-ff47-405e-9301-22d11a1be499']");
    By roleAndPageAuthorizationPageReportHistoryCheckbox = By.cssSelector("[value='8c53c171-2784-4e89-9505-2c463601e031']");
    By roleAndPageAuthorizationPageGetReportStatusByReportIdCheckbox = By.cssSelector("[value='e4e9a816-4869-4c3e-938f-dc627940bdce']");
    By roleAndPageAuthorizationPageGetReportStatusCheckbox = By.cssSelector("[value='5e868a51-cd8d-48af-bc8e-88c329d7a935']");
    By roleAndPageAuthorizationPageGetReportFileCheckbox = By.cssSelector("[value='dd85a51e-cb68-49e8-b472-53127b4d0175']");
    By roleAndPageAuthorizationPageTransactionTranscriptReportCheckbox = By.cssSelector("[value='b503434a-e3b0-4210-8e60-e0c6a495835e']");
    By roleAndPageAuthorizationPageCreateProtectedAmountViewReportStatementCheckbox = By.cssSelector("[value='0db777f7-6854-4bf3-91f1-ab4cd0bf369f']");
    By roleAndPageAuthorizationPageExportProtectedAmountViewReportStatementCheckbox = By.cssSelector("[value='1624784a-5501-41c2-add1-558dde080a9f']");
    By roleAndPageAuthorizationPageBillingSummaryCheckbox = By.cssSelector("[value='89b19d90-8e32-4f02-8d52-bfb4090358d2']");
    By roleAndPageAuthorizationPageCreateBillingSummaryReportCheckbox = By.cssSelector("[value='13b57234-0649-4dbd-87fd-77581c87c83a']");
    By roleAndPageAuthorizationPageExportBillingSummaryReportCheckbox = By.cssSelector("[value='24dc7c6e-1fc3-435d-8ff4-ae824e34e0f2']");
    By roleAndPageAuthorizationPagePosSolutionCheckbox = By.cssSelector("[value='d792e9f2-6b61-461b-b27d-8b027e8b1262']");
    By roleAndPageAuthorizationPageCreatePosReleaseSummaryReportCheckbox = By.cssSelector("[value='9deb07cf-01dc-40b6-b23e-b5e3c294a1fd']");
    By roleAndPageAuthorizationPageExportPosReleaseSummaryReportCheckbox = By.cssSelector("[value='6db34612-9720-41ff-8f27-e935ac7510b3']");
    By roleAndPageAuthorizationPagePosSummaryCheckbox = By.cssSelector("[value='7ff240d2-f20e-45d5-852f-c32f8c83c5fb']");
    By roleAndPageAuthorizationPageCreatePosTransactionSummaryReportCheckbox = By.cssSelector("[value='e57ca590-c296-4b61-a390-f22994bd44cb']");
    By roleAndPageAuthorizationPageExportPosTransactionSummaryReportCheckbox = By.cssSelector("[value='70be587a-3835-4fd3-8d64-3a575e2b72d4']");
    By roleAndPageAuthorizationPageMerchantEntitlementCheckbox = By.cssSelector("[value='6945f375-0594-4703-a33c-0db7ba85b4b8']");
    By roleAndPageAuthorizationPageCreateMerchantEntitlementCheckbox = By.cssSelector("[value='ca0494ef-8ec1-48c5-b00f-2c53ce36cec1']");
    By roleAndPageAuthorizationPageExportMerchantEntitlementReportCheckbox = By.cssSelector("[value='fa8f852e-62fd-4d5e-b087-b1e289fd3442']");
    By roleAndPageAuthorizationPageProtectedAmountCheckbox = By.cssSelector("[value='fa93eb3d-e29d-4cd1-a150-cc44275314c1']");
    By roleAndPageAuthorizationPageCreateProtectedAmountViewReportCheckbox = By.cssSelector("[value='b46fec12-b03e-43c4-b8b5-a9c0784030cc']");
    By roleAndPageAuthorizationPageExportProtectedAmountViewReportCheckbox = By.cssSelector("[value='22dc51d2-a0ab-4cc6-a0b2-d4c896a1e1d5']");
    By roleAndPageAuthorizationPageEMoneyProtectedAmountBalanceReportCheckbox = By.cssSelector("[value='2a78f376-f5dc-4a22-b367-bfb31fe564c4']");
    By roleAndPageAuthorizationPageCreateEMoneyProtectedAmountBalanceReportCheckbox = By.cssSelector("[value='aeba0b2b-84d4-4147-b8ee-ed82b3278c45']");
    By roleAndPageAuthorizationPageExportEMoneyProtectedAmountBalanceReportCheckbox = By.cssSelector("[value='11760ba9-46bf-4e34-afa2-be54fd885f8a']");
    By roleAndPageAuthorizationPageFraudCheckbox = By.cssSelector("[value='14f8f95c-fa30-415b-8639-0205c0a124e5']");
    By roleAndPageAuthorizationPageFraudRulesCheckbox = By.cssSelector("[value='7befd334-8cd1-4ad4-9b51-c0b3908296f9']");
    By roleAndPageAuthorizationPageListFraudCheckbox = By.cssSelector("[value='d6dc4f3b-f9ea-4c07-8192-0ce59931b21f']");
    By roleAndPageAuthorizationPageUpdateFraudCheckbox = By.cssSelector("[value='dea516d0-e64b-4ac2-9cc5-d0f43be13f53']");
    By roleAndPageAuthorizationPageCreateFraudCheckbox = By.cssSelector("[value='52b66773-be16-4d2b-b28e-39b94ade02f9']");
    By roleAndPageAuthorizationPageExportFraudTransactionCheckbox = By.cssSelector("[value='bc3eed9b-e874-4c07-9daa-869814b43c75']");
    By roleAndPageAuthorizationPageExportFraudCheckbox = By.cssSelector("[value='643344f1-c243-4e26-933b-a16ed623dab4']");
    By roleAndPageAuthorizationPageFraudManagementCheckbox = By.cssSelector("[value='bab95c5d-7bdb-43ff-823a-f7590bd2b2f8']");
    By roleAndPageAuthorizationPageFraudManagementListFraudCheckbox = By.cssSelector("[value='fa722c5d-a821-42e1-a522-c56bcb61a1b0']");
    By roleAndPageAuthorizationPageFraudManagementListFraudTransactionCheckbox = By.cssSelector("[value='d2e40c26-0af5-448f-88b4-b1bbe57b2519']");
    By roleAndPageAuthorizationPageChargebackCheckbox = By.cssSelector("[value='4e07b35e-d55c-43c3-9861-d2e1665bee73']");
    By roleAndPageAuthorizationPageChargebackManagementCheckbox = By.cssSelector("[value='0eca62b5-b231-4ff1-b28a-a4d7129b1fc7']");
    By roleAndPageAuthorizationPageListChargebackCheckbox = By.cssSelector("[value='b953d2de-f63e-4ff9-872d-4f6c110039af']");
    By roleAndPageAuthorizationPageCreateChargebackCheckbox = By.cssSelector("[value='31af8e5d-8dd3-4f2e-a560-e55d7b168490']");
    By roleAndPageAuthorizationPageListChargebackDetailsCheckbox = By.cssSelector("[value='c4b24662-f20c-468d-a6b6-4a3b17a8e4c1']");
    By roleAndPageAuthorizationPageExportChargebackTransactionCheckbox = By.cssSelector("[value='4980936f-3329-43e7-90e9-567eb1635cd8']");
    By roleAndPageAuthorizationPagePendingApprovalsListCheckbox = By.cssSelector("[value='2892de27-e5b0-4f6c-b1ed-b59c86d1722b']");
    By roleAndPageAuthorizationPageChargebackUpdateCheckbox = By.cssSelector("[value='3d619adb-fe41-4ca5-8862-764137d05340']");
    By roleAndPageAuthorizationPageListChargebackPendingCheckbox = By.cssSelector("[value='33047936-5069-4409-aa77-9ac7dc64bbd4']");

    public void roleAndPageAuthorizationPageAllElementsAreDisplayed() {
        isElementDisplay(roleAndPageAuthorizationPageChargebackCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageChargebackManagementCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageListChargebackCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageCreateChargebackCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageListChargebackDetailsCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageExportChargebackTransactionCheckbox);
        isElementDisplay(roleAndPageAuthorizationPagePendingApprovalsListCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageChargebackUpdateCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageListChargebackPendingCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageFraudCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageFraudRulesCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageListFraudCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageUpdateFraudCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageCreateFraudCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageExportFraudTransactionCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageExportFraudCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageFraudManagementCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageFraudManagementListFraudCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageFraudManagementListFraudTransactionCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageProtectedAmountCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageCreateProtectedAmountViewReportCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageExportProtectedAmountViewReportCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageEMoneyProtectedAmountBalanceReportCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageCreateEMoneyProtectedAmountBalanceReportCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageExportEMoneyProtectedAmountBalanceReportCheckbox);
        isElementDisplay(roleAndPageAuthorizationPagePosSummaryCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageCreatePosTransactionSummaryReportCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageExportPosTransactionSummaryReportCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageMerchantEntitlementCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageCreateMerchantEntitlementCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageExportMerchantEntitlementReportCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageBillingSummaryCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageCreateBillingSummaryReportCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageExportBillingSummaryReportCheckbox);
        isElementDisplay(roleAndPageAuthorizationPagePosSolutionCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageCreatePosReleaseSummaryReportCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageExportPosReleaseSummaryReportCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageGetReportFileCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageTransactionTranscriptReportCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageCreateProtectedAmountViewReportStatementCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageExportProtectedAmountViewReportStatementCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageGetManualCorrectionCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageCreateManualCorrectionCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageReportHistoryCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageGetReportStatusByReportIdCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageGetReportStatusCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageReportsCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageMerchantPayoutReportsCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageCreatePayoutTransactionCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageCreatePayoutReportCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageFinanceAndAccountingManualAdjustmentCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageMerchantManagementCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageMerchantsCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageListMerchantsCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageExportCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageUpdateMerchantStatusCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageGetMerchantCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageUpdateMerchantCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageGetSubMerchantDetailCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageListSubMerchantCheckbox);
        isElementDisplay(roleAndPageAuthorizationPagePaymentRecordsCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageGetPaymentCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageGetDetailsOfPaymentCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageExportPaymentCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageCreatePaymentCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageSoftPosCreateRefundCheckbox);
        isElementDisplay(roleAndPageAuthorizationPagePaymentTransactionsCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageGetDetailsOfTransactionCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageGetPaymentTransactionsCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageExportPaymentTransactionsCheckbox);
        isElementDisplay(roleAndPageAuthorizationPagePaymentManagementCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageBankManagementCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageCreateBankCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageExportBankCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageUpdateBankCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageGetBankCheckbox);
        isElementDisplay(roleAndPageAuthorizationPagePosManagementCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageGetPosCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageUpdatePosCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageGetDetailsOfPosCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageCreatePosCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageExportPosCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageWaitingApprovalsCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageMakerAndCheckerCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageMakerAndCheckerExportCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageDownloadFilesCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageUpdateMakerAndCheckerCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageListMakerAndCheckerCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageUserGroupAndRoleAuthorizationCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageAddRoleToUserGroupCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageRoleAndPageManagementCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageGetPermissionForRoleAndPageCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageAddPermissionForRoleAndPageCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageUserGroupManagementCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageUpdateUserGroupCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageFetchSelectedUserGroupCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageDeletedSelectedUserGroupCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageListUserGroupCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageCreateUserGroupCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageRoleManagementCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageDeletedSelectedRolesCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageCreateRoleCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageFetchSelectedRoleCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageUpdateRoleCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageListMakerAndCheckerPendingCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageLoginManagementCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageUserManagementCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageForgetPasswordCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageUpdatePasswordCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageDeletedSelectedUserCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageGetUserByIdCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageNewPasswordCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageListUserCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageUpdateUserCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageExportUserCheckbox);
        isElementDisplay(roleAndPageAuthorizationPageSaveButton);
        isElementDisplay(roleAndPageAuthorizationPageRoleName);
        isElementDisplay(roleAndPageAuthorizationPageModuleName);
    }

    public void roleAndPageAuthorizationPageControlUrl() throws Exception {
        controlUrl("role-permission", "pages.roleandpageauthorization");
    }

    public void leftSubMenuRoleAndPageAuthorizationSubmit() {
        click(roleAndPageAuthorizationPageSubLeftMenuButton);
        waitBySeconds(2);
    }
}
